name: 'CI-master'

on:
  push:
    branches:
      - main

jobs:
  master-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # default 360
    steps:
    - uses: actions/checkout@v1
      with:
        ref: 'main'
    - name: Install Java 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
    - name: 'CI Build Command'
      timeout-minutes: 20
      run: |
        ./ci-build.sh